export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_ALL_NOTIFICATION = 'DELETE_ALL_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
export const GET_NOTIFICATIONS_VALUE = 'GET_NOTIFICATIONS_VALUE';
